import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "@/app/(components)/SessionProvider";
import Navbar from "../(components)/Navbar";
import { redirect } from "next/navigation";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CSnips",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session) {
    redirect("/");
  }
  return (
    <SessionProvider session={session}>
      <div className="flex flex-col w-full h-full">
        <Navbar />
        {children}
      </div>
    </SessionProvider>
  );
}
